# Generated by Django 4.2.4 on 2023-08-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Resolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('Image', 'Image'), ('Music', 'Music'), ('Notification', 'Notification')], default='Image', max_length=15)),
                ('file_view', models.FileField(blank=True, null=True, upload_to='files/%Y%m%d/%H%M%S/')),
                ('Recommended', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='Resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.resolutions'),
        ),
        migrations.AddField(
            model_name='categories',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categories'),
        ),
    ]
