# Generated by Django 4.2.4 on 2023-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorage',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
