# Generated by Django 4.2.4 on 2023-08-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datastorage_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorage',
            name='file_view',
            field=models.FileField(blank=True, null=True, upload_to='files/<django.db.models.fields.CharField>/%Y%m%d/%H%M%S/'),
        ),
    ]
