# Generated by Django 4.2.4 on 2023-08-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_datastorage_file_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorage',
            name='file_view',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y%m%d/%H%M%S/'),
        ),
    ]
