# Generated by Django 4.2.4 on 2023-08-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_datastorage_file_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastorage',
            name='file_url',
        ),
    ]
