# Generated by Django 4.2.4 on 2023-08-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_datastorage_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastorage',
            name='type_of',
        ),
        migrations.AddField(
            model_name='categories',
            name='type_of',
            field=models.CharField(choices=[('Image', 'Image'), ('Music', 'Music'), ('Notification', 'Notification')], default='Image', max_length=15),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='Resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.resolutions'),
        ),
    ]
