# Generated by Django 4.2.4 on 2023-08-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='parent_category',
            new_name='image_id',
        ),
    ]
